### PR TITLE
travis unity install

### PR DESCRIPTION
**Pull request by dannyflax**
This PR does two things:
1. Fix the current unity build
2. Enables continuous integration so we can see whether or not the build is broken

### CODE REVIEW

**Comment by Amperial** [comment]
Crazy that travis provides 40GB for free build instances

**Comment by dannyflax** [comment]
@Amperial  we might need it lol

**Comment by dannyflax** [comment]
FYI, builds might take a while because Travis literally has to install all of unity. I set it up to also install plugins for windows + linux building but tbh might get rid of that to decrease the overhead

**Comment by dannyflax** [comment]
^check the Travis stack for commit e0e315f. Actual compilation errors! This is what we want!

**Pull request merged**
