### PR TITLE
added outline to all scenes

### PR DESCRIPTION
**Pull request by utomorezeki**

### CODE REVIEW

**Comment by utomorezeki** [comment]
I forgot to add, this PR also adjust RSLevel camera

**Comment by dannyflax** [comment]
the outlines don't appear for me :(

**Comment by dannyflax** [comment]
oh I was being dumb, you need to run it from the master scene

**Comment by dannyflax** [comment]
Looks cool. Do we want to apply it to the 2D character too so we can see it behind walls?

**Pull request merged**
